chore: Update release workflow file

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,13 +1,52 @@
-name: ci
+name: Release
 
 on:
-  push:
+  workflow_dispatch:
 
 jobs:
   docker:
     runs-on: ubuntu-latest
     environment: prod1
     steps:
+      - name: "Checkout"
+        uses: actions/checkout@v6
+
+      - name: "Setup Node"
+        uses: actions/setup-node@v6
+        with:
+          node-version: 24
+
+      - name: "Install PNPM"
+        uses: pnpm/action-setup@v6
+        with:
+          version: latest
+
+      - name: "Install Dependencies"
+        run: pnpm install
+
+      - name: "Process Changesets"
+        id: release
+        run: |
+          git config user.name "notedeck[bot]"
+          git config user.email "76795128+notedeck[bot]@users.noreply.github.com"
+
+          pnpm changeset:version
+
+          git add -A
+
+          if git diff --cached --quiet && git diff --quiet; then
+            echo "No changes to commit."
+            exit 0
+          fi
+
+          git commit -m "ci: Process changesets"
+          git push origin HEAD:main || exit 1  # Fail if push fails
+
+          VERSION=$(node -p "require('./package.json').version")
+          echo "semver=${VERSION}" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Login to AB Internal Registry
         uses: docker/login-action@v4
         with:
@@ -15,16 +54,11 @@ jobs:
           username: ${{ vars.AB_INT_REGISTRY_USER }}
           password: ${{ secrets.AB_INT_REGISTRY_PASS }}
 
-      # - name: Set up QEMU
-      #   uses: docker/setup-qemu-action@v4
-
-      # - name: Set up Docker Buildx
-      #   uses: docker/setup-buildx-action@v4
-
-      - name: Build and push
+      - name: Build & Push
         uses: docker/build-push-action@v7
         with:
           platforms: linux/amd64
           push: true
           tags: |
-            registry1.abiddiscombe.dev/web:latest
+            ${{ vars.AB_INT_REGISTRY_HOST }}/web:latest
+            ${{ vars.AB_INT_REGISTRY_HOST }}/web:${{ steps.release.outputs.semver }}
